# Generated by Django 4.0.5 on 2022-12-04 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_pageposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagepost', to='network.pageposts'),
        ),
    ]
