# Generated by Django 4.0.5 on 2022-12-04 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_page_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='posts',
        ),
        migrations.AddField(
            model_name='pageposts',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='network.page'),
        ),
    ]
