# Generated by Django 4.1.3 on 2022-12-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_remove_pageposts_page_page_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Product_Price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
