# Generated by Django 4.1.3 on 2022-12-06 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_post_product_price_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Product_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
