# Generated by Django 4.1.3 on 2022-12-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_post_posts_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='posts',
        ),
    ]
