# Generated by Django 4.1.3 on 2022-12-08 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0026_remove_page_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network.page'),
        ),
    ]
