# Generated by Django 4.1.3 on 2022-12-08 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0028_alter_post_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network.page'),
        ),
    ]
