# Generated by Django 4.1.3 on 2022-12-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0029_post_page_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers'),
        ),
    ]
