# Generated by Django 4.1.3 on 2022-12-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0032_alter_user_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(default='card2.webp', upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
