# Generated by Django 4.1.3 on 2022-12-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0033_alter_user_cover_alter_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
