# Generated by Django 4.1.3 on 2022-12-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0034_remove_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
    ]
